# First dive: *Le Petit Prince* MEG listening dataset

## Introduction

This dataset (OpenNeuro `ds007523`) contains **magnetoencephalography (MEG)** recordings
of participants listening to the French audiobook *Le Petit Prince*, by Antoine de
Saint-Exupéry. It is analyzed in d'Ascoli et al., *Towards decoding individual words
from non-invasive brain recordings*, Nature Communications 16, 10521 (2025).

A complementary MEG dataset using a reading (RSVP) paradigm from the same project is
available as `ds007524`.

**Key facts:**

- **Participants**: 58 healthy adults (17 female, mean age 27.8 ± 5.5 years), all
  native French speakers, right-handed, no neurological disorders.
- **Stimulus**: the audiobook, split into 9 parts (~10min50s ± 55s each, range
  9min40s–12min30s).
- **Task**: participants passively listened to one audiobook part per run (9 runs
  total), with 4 comprehension questions between runs and short breaks.
- **MEG system**: Elekta Neuromag TRIUX (102 magnetometers + 204 planar
  gradiometers), sampled at 1000 Hz, online band-pass 0.1–330 Hz. EOG/ECG were
  recorded alongside for artifact monitoring.
- **Anatomy**: a T1-weighted MRI per participant (3T Siemens Prisma) for
  coregistration/source analysis.
- Data follow the **BIDS/MEG-BIDS** standard.

The goal of this notebook is just to get familiar with the dataset's structure and
contents (participants, files, basic MEG file info) — not to perform any analysis.

In [1]:
import sys
sys.path.append('..')

import json
import pandas as pd
import mne

from config import LISTEN_DIR

LISTEN_DIR

PosixPath('/mnt/sda/data-output/phd/Pallier2025/listen/ds007523-download')

## Participants

The `participants.tsv` file at the dataset root lists demographics for all 58
subjects.

In [2]:
participants = pd.read_csv(LISTEN_DIR / 'participants.tsv', sep='\t')
print(f"{len(participants)} participants")
participants.describe(include='all')

58 participants

       participant_id        age  sex hand
count              58  58.000000   58   58
unique             58        NaN    2    1
top            sub-01        NaN    M    R
freq                1        NaN   39   58
mean              NaN  27.793103  NaN  NaN
std               NaN   5.479655  NaN  NaN
min               NaN  18.000000  NaN  NaN
25%               NaN  23.000000  NaN  NaN
50%               NaN  28.500000  NaN  NaN
75%               NaN  32.000000  NaN  NaN
max               NaN  43.000000  NaN  NaN

## Data organization and complete file-content preview

Each subject has a `ses-01/` session with MEG recordings and, when available, an anatomical MRI. The MEG folder contains up to nine listening runs. A typical run has four files: the MEG recording (`*_meg.fif`), its JSON metadata, `events.tsv`, and `channels.tsv`; session-level MEG calibration, crosstalk, and coordinate-system files are also present. The shared sourcedata contains stimulus materials and run-level extra information.

The inventory below previews every file found under `LISTEN_DIR`, including every subject and run. Tables show their first five rows, text and JSON show an opening excerpt, and binary files show readable metadata or header bytes where possible. This keeps the actual content visible while making it clear which files are text-readable and which are binary recordings or images.

In [3]:
import re

all_files = sorted(path for path in LISTEN_DIR.rglob('*') if path.is_file())
subject_dirs = sorted(path for path in LISTEN_DIR.glob('sub-*') if path.is_dir())
subject_file_sets = {
    subject.name: {
        path.relative_to(LISTEN_DIR).as_posix()
        for path in subject.rglob('*')
        if path.is_file()
    }
    for subject in subject_dirs
}

dataset_level_files = [
    path.relative_to(LISTEN_DIR).as_posix()
    for path in all_files
    if not path.relative_to(LISTEN_DIR).parts[0].startswith('sub-')
]
print(f"{len(all_files):,} files across {len(subject_dirs)} subjects")
print(f"\nDataset-level files ({len(dataset_level_files)}):")
print('\n'.join(dataset_level_files))

representative_subject = subject_dirs[0]
print(f"\nComplete subject example: {representative_subject.name}")
for path in sorted(representative_subject.rglob('*')):
    if path.is_file():
        print(path.relative_to(LISTEN_DIR).as_posix())

normalized_paths = {
    subject: {re.sub(r'sub-\d+', 'sub-XX', path) for path in paths}
    for subject, paths in subject_file_sets.items()
}
all_subject_patterns = sorted(set.union(*normalized_paths.values()))
pattern_rows = []
for pattern in all_subject_patterns:
    present = sorted(
        subject for subject, paths in normalized_paths.items() if pattern in paths
    )
    example_path = next(
        path for path in subject_file_sets[present[0]]
        if re.sub(r'sub-\d+', 'sub-XX', path) == pattern
    )
    pattern_rows.append({
        'subject path pattern': pattern,
        'subjects containing file': len(present),
        'example path': example_path,
    })
print('\nSubject-specific path patterns (shared layouts shown once):')
with pd.option_context('display.max_colwidth', None):
    display(pd.DataFrame(pattern_rows))

missing_rows = []
for pattern in all_subject_patterns:
    missing = sorted(
        subject for subject, paths in normalized_paths.items() if pattern not in paths
    )
    if missing:
        missing_rows.append({
            'path pattern': pattern,
            'missing subjects': ', '.join(missing),
        })
print('\nExceptions to the shared subject layout:')
if missing_rows:
    with pd.option_context('display.max_colwidth', None):
        display(pd.DataFrame(missing_rows))
else:
    print('No missing subject paths.')

coverage_rows = []
for subject in subject_dirs:
    subject_meg_dir = subject / 'ses-01' / 'meg'
    complete_runs = []
    incomplete_runs = []
    for run in range(1, 10):
        prefix = f"{subject.name}_ses-01_task-listen_run-{run:02d}"
        required_files = [
            subject_meg_dir / f'{prefix}{suffix}'
            for suffix in ('_channels.tsv', '_events.tsv', '_meg.fif', '_meg.json')
        ]
        if all(path.is_file() for path in required_files):
            complete_runs.append(run)
        else:
            missing_suffixes = [
                path.name.removeprefix(prefix)
                for path in required_files
                if not path.is_file()
            ]
            incomplete_runs.append(
                f"{run:02d} (missing {', '.join(missing_suffixes)})"
            )
    coverage_rows.append({
        'subject': subject.name,
        'files': len(subject_file_sets[subject.name]),
        'T1w MRI': (subject / 'ses-01' / 'anat' / f'{subject.name}_ses-01_T1w.nii.gz').is_file(),
        'complete runs': len(complete_runs),
        'incomplete runs': '; '.join(incomplete_runs) or '—',
    })
print('\nFile and recording coverage by subject:')
display(pd.DataFrame(coverage_rows))

2,506 files across 58 subjects

Dataset-level files (91):
.datalad/config
.gitattributes
CHANGES
LICENSE
README
datacite.yml
dataset_description.json
participants.json
participants.tsv
sourcedata/stimuli/audio/ch1-3.wav
sourcedata/stimuli/audio/ch10-12.wav
sourcedata/stimuli/audio/ch13-14.wav
sourcedata/stimuli/audio/ch15-19.wav
sourcedata/stimuli/audio/ch20-22.wav
sourcedata/stimuli/audio/ch23-25.wav
sourcedata/stimuli/audio/ch26-27.wav
sourcedata/stimuli/audio/ch4-6.wav
sourcedata/stimuli/audio/ch7-9.wav
sourcedata/stimuli/data_path.txt
sourcedata/stimuli/offset_stretch/infos.csv
sourcedata/stimuli/origin.txt
sourcedata/stimuli/phonemes/ch1-3.TextGrid
sourcedata/stimuli/phonemes/ch10-12.TextGrid
sourcedata/stimuli/phonemes/ch13-14.TextGrid
sourcedata/stimuli/phonemes/ch15-19.TextGrid
sourcedata/stimuli/phonemes/ch20-22.TextGrid
sourcedata/stimuli/phonemes/ch23-25.TextGrid
sourcedata/stimuli/phonemes/ch26-27.TextGrid
sourcedata/stimuli/phonemes/ch4-6.TextGrid
sourcedata/stimuli/phonemes/ch7-9.TextGrid
sourcedata/stimuli/requirements.txt
sourcedata/stimuli/syntax/README.md
sourcedata/stimuli/syntax/ch1-3.syntax.txt
sourcedata/stimuli/syntax/ch10-12.syntax.txt
sourcedata/stimuli/syntax/ch13-14.syntax.txt
sourcedata/stimuli/syntax/ch15-19.syntax.txt
sourcedata/stimuli/syntax/ch20-22.syntax.txt
sourcedata/stimuli/syntax/ch23-25.syntax.txt
sourcedata/stimuli/syntax/ch26-27.syntax.txt
sourcedata/stimuli/syntax/ch4-6.syntax.txt
sourcedata/stimuli/syntax/ch7-9.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run0_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run1_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run2_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run3_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run4_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run5_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run6_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run7_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run8_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_no_punct/run9_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/frtok.py
sourcedata/stimuli/syntax_new_untested/make.sh
sourcedata/stimuli/syntax_new_untested/run1_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/run2_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/run3_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/run4_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/run5_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/run6_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/run7_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/run8_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/run9_v2_0.25_0.5-tokenized.syntax.txt
sourcedata/stimuli/syntax_new_untested/tsv_to_txt.py
sourcedata/stimuli/txt_laser/run1.txt
sourcedata/stimuli/txt_laser/run2.txt
sourcedata/stimuli/txt_laser/run3.txt
sourcedata/stimuli/txt_laser/run4.txt
sourcedata/stimuli/txt_laser/run5.txt
sourcedata/stimuli/txt_laser/run6.txt
sourcedata/stimuli/txt_laser/run7.txt
sourcedata/stimuli/txt_laser/run8.txt
sourcedata/stimuli/txt_laser/run9.txt
sourcedata/stimuli/txt_raw/ch1-3.txt
sourcedata/stimuli/txt_raw/ch10-12.txt
sourcedata/stimuli/txt_raw/ch13-14.txt
sourcedata/stimuli/txt_raw/ch15-19.txt
sourcedata/stimuli/txt_raw/ch20-22.txt
sourcedata/stimuli/txt_raw/ch23-25.txt
sourcedata/stimuli/txt_raw/ch26-27.txt
sourcedata/stimuli/txt_raw/ch4-6.txt
sourcedata/stimuli/txt_raw/ch7-9.txt
sourcedata/task-listen_run-01_extra_info.tsv
sourcedata/task-listen_run-02_extra_info.tsv
sourcedata/task-listen_run-03_extra_info.tsv
sourcedata/task-listen_run-04_extra_info.tsv
sourcedata/task-listen_run-05_extra_info.tsv
sourcedata/task-listen_run-06_extra_info.tsv
sourcedata/task-listen_run-07_extra_info.tsv
sourcedata/task-listen_run-08_extra_info.tsv
sourcedata/task-listen_run-09_extra_info.tsv
task-listen_events.json

Complete subject example: sub-01
sub-01/ses-01/anat/sub-01_ses-01_T1w.json
sub-01/ses-01/anat/sub-01_ses-01_T1w.nii.gz
sub-01/ses-01/meg/sub-01_ses-01_acq-calibration_meg.dat
sub-01/ses-01/meg/sub-01_ses-01_acq-crosstalk_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_coordsystem.json
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-01_channels.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-01_events.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-01_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-01_meg.json
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-02_channels.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-02_events.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-02_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-02_meg.json
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-03_channels.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-03_events.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-03_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-03_meg.json
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-04_channels.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-04_events.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-04_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-04_meg.json
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-05_channels.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-05_events.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-05_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-05_meg.json
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-06_channels.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-06_events.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-06_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-06_meg.json
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-07_channels.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-07_events.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-07_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-07_meg.json
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-08_channels.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-08_events.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-08_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-08_meg.json
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-09_channels.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-09_events.tsv
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-09_meg.fif
sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-09_meg.json
sub-01/ses-01/sub-01_ses-01_scans.tsv

Subject-specific path patterns (shared layouts shown once):

,subject path pattern,subjects containing file,example path
0,sub-XX/ses-01/anat/sub-XX_ses-01_T1w.json,49,sub-01/ses-01/anat/sub-01_ses-01_T1w.json
1,sub-XX/ses-01/anat/sub-XX_ses-01_T1w.nii.gz,49,sub-01/ses-01/anat/sub-01_ses-01_T1w.nii.gz
2,sub-XX/ses-01/meg/sub-XX_ses-01_acq-calibration_meg.dat,58,sub-01/ses-01/meg/sub-01_ses-01_acq-calibration_meg.dat
3,sub-XX/ses-01/meg/sub-XX_ses-01_acq-crosstalk_meg.fif,58,sub-01/ses-01/meg/sub-01_ses-01_acq-crosstalk_meg.fif
4,sub-XX/ses-01/meg/sub-XX_ses-01_coordsystem.json,58,sub-01/ses-01/meg/sub-01_ses-01_coordsystem.json
5,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-01_channels.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-01_channels.tsv
6,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-01_events.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-01_events.tsv
7,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-01_meg.fif,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-01_meg.fif
8,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-01_meg.json,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-01_meg.json
9,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-02_channels.tsv,57,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-02_channels.tsv
10,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-02_events.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-02_events.tsv
11,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-02_meg.fif,57,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-02_meg.fif
12,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-02_meg.json,57,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-02_meg.json
13,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-03_channels.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-03_channels.tsv
14,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-03_events.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-03_events.tsv
15,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-03_meg.fif,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-03_meg.fif
16,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-03_meg.json,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-03_meg.json
17,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-04_channels.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-04_channels.tsv
18,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-04_events.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-04_events.tsv
19,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-04_meg.fif,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-04_meg.fif
20,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-04_meg.json,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-04_meg.json
21,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-05_channels.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-05_channels.tsv
22,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-05_events.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-05_events.tsv
23,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-05_meg.fif,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-05_meg.fif
24,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-05_meg.json,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-05_meg.json
25,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-06_channels.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-06_channels.tsv
26,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-06_events.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-06_events.tsv
27,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-06_meg.fif,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-06_meg.fif
28,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-06_meg.json,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-06_meg.json
29,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-07_channels.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-07_channels.tsv
30,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-07_events.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-07_events.tsv
31,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-07_meg.fif,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-07_meg.fif
32,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-07_meg.json,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-07_meg.json
33,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-08_channels.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-08_channels.tsv
34,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-08_events.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-08_events.tsv
35,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-08_meg.fif,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-08_meg.fif
36,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-08_meg.json,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-08_meg.json
37,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-09_channels.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-09_channels.tsv
38,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-09_events.tsv,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-09_events.tsv
39,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-09_meg.fif,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-09_meg.fif
40,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-09_meg.json,58,sub-01/ses-01/meg/sub-01_ses-01_task-listen_run-09_meg.json
41,sub-XX/ses-01/sub-XX_ses-01_scans.tsv,58,sub-01/ses-01/sub-01_ses-01_scans.tsv

Exceptions to the shared subject layout:

,path pattern,missing subjects
0,sub-XX/ses-01/anat/sub-XX_ses-01_T1w.json,"sub-21, sub-22, sub-40, sub-42, sub-43, sub-44, sub-46, sub-48, sub-56"
1,sub-XX/ses-01/anat/sub-XX_ses-01_T1w.nii.gz,"sub-21, sub-22, sub-40, sub-42, sub-43, sub-44, sub-46, sub-48, sub-56"
2,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-02_channels.tsv,sub-56
3,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-02_meg.fif,sub-56
4,sub-XX/ses-01/meg/sub-XX_ses-01_task-listen_run-02_meg.json,sub-56

File and recording coverage by subject:

,subject,files,T1w MRI,complete runs,incomplete runs
0,sub-01,42,True,9,—
1,sub-02,42,True,9,—
2,sub-03,42,True,9,—
3,sub-04,42,True,9,—
4,sub-05,42,True,9,—
5,sub-06,42,True,9,—
6,sub-07,42,True,9,—
7,sub-08,42,True,9,—
8,sub-09,42,True,9,—
9,sub-10,42,True,9,—
10,sub-11,42,True,9,—
11,sub-12,42,True,9,—
12,sub-13,42,True,9,—
13,sub-14,42,True,9,—
14,sub-15,42,True,9,—
15,sub-16,42,True,9,—
16,sub-17,42,True,9,—
17,sub-18,42,True,9,—
18,sub-19,42,True,9,—
19,sub-20,42,True,9,—
20,sub-21,40,False,9,—
21,sub-22,40,False,9,—
22,sub-23,42,True,9,—
23,sub-24,42,True,9,—
24,sub-25,42,True,9,—
25,sub-26,42,True,9,—
26,sub-27,42,True,9,—
27,sub-28,42,True,9,—
28,sub-29,42,True,9,—
29,sub-30,42,True,9,—
30,sub-31,42,True,9,—
31,sub-32,42,True,9,—
32,sub-33,42,True,9,—
33,sub-34,42,True,9,—
34,sub-35,42,True,9,—
35,sub-36,42,True,9,—
36,sub-37,42,True,9,—
37,sub-38,42,True,9,—
38,sub-39,42,True,9,—
39,sub-40,40,False,9,—
40,sub-41,42,True,9,—
41,sub-42,40,False,9,—
42,sub-43,40,False,9,—
43,sub-44,40,False,9,—
44,sub-45,42,True,9,—
45,sub-46,40,False,9,—
46,sub-47,42,True,9,—
47,sub-48,40,False,9,—
48,sub-49,42,True,9,—
49,sub-50,42,True,9,—
50,sub-51,42,True,9,—
51,sub-52,42,True,9,—
52,sub-53,42,True,9,—
53,sub-54,42,True,9,—
54,sub-55,42,True,9,—
55,sub-56,37,False,8,"02 (missing _channels.tsv, _meg.fif, _meg.json)"
56,sub-57,42,True,9,—
57,sub-58,42,True,9,—

In [4]:
import gzip
import struct
import wave


def shorten(value, limit=140):
    text = str(value).replace('\n', ' ')
    return text if len(text) <= limit else text[:limit - 1] + '…'


def file_preview(path):
    size = path.stat().st_size

    if path.suffix.lower() in {'.tsv', '.csv'}:
        separator = '\t' if path.suffix.lower() == '.tsv' else ','
        frame = pd.read_csv(path, sep=separator, nrows=5)
        frame = frame.map(shorten)
        return frame.to_string(index=False).replace('\n', ' | ')

    if path.suffix.lower() == '.json':
        contents = json.dumps(json.loads(path.read_text()), ensure_ascii=False)
        return shorten(contents, 700)

    if path.name.endswith('.nii.gz'):
        with gzip.open(path, 'rb') as file:
            header = file.read(352)
        little_size = struct.unpack('<i', header[:4])[0]
        endian = '<' if little_size == 348 else '>'
        dimensions = struct.unpack(f'{endian}8h', header[40:56])
        voxel_sizes = struct.unpack(f'{endian}8f', header[76:108])
        return (f"NIfTI-1 dimensions={dimensions[1:dimensions[0] + 1]}, "
                f"voxel sizes (mm)={voxel_sizes[1:dimensions[0] + 1]}; "
                f"header bytes={header[:16].hex(' ')}")

    if path.suffix.lower() == '.wav':
        with wave.open(str(path), 'rb') as audio:
            channels = audio.getnchannels()
            sample_width = audio.getsampwidth()
            frames = audio.readframes(4)
            sample_format = {1: 'B', 2: 'h', 4: 'i'}.get(sample_width)
            samples = (
                struct.unpack('<' + sample_format * (len(frames) // sample_width), frames)
                if sample_format else frames.hex(' ')
            )
            return (f"WAV: {channels} channels, {audio.getframerate()} Hz, "
                    f"{audio.getnframes():,} frames, {sample_width} bytes/sample; "
                    f"first samples={samples}")

    if path.suffix.lower() in {'.fif', '.dat'}:
        with path.open('rb') as file:
            first_bytes = file.read(32)
        try:
            text = path.read_text(encoding='utf-8')
            if '\x00' not in text:
                return ' | '.join(shorten(line, 160) for line in text.splitlines()[:5])
        except UnicodeError:
            pass
        return f"Binary data ({size:,} bytes); first 32 bytes={first_bytes.hex(' ')}"

    try:
        lines = path.read_text(encoding='utf-8').splitlines()
        preview = ' | '.join(shorten(line, 180) for line in lines[:5])
        return preview + (f" | … ({len(lines) - 5} more lines)" if len(lines) > 5 else '')
    except UnicodeError:
        with path.open('rb') as file:
            first_bytes = file.read(32)
        return f"Binary data ({size:,} bytes); first 32 bytes={first_bytes.hex(' ')}"


preview_rows = []
for path in all_files:
    try:
        preview = file_preview(path)
    except Exception as error:
        preview = f"Preview error: {type(error).__name__}: {error}"
    preview_rows.append({
        'file': path.relative_to(LISTEN_DIR).as_posix(),
        'size (bytes)': path.stat().st_size,
        'head / content preview': preview,
    })

print(f"Content previews for all {len(preview_rows):,} files under LISTEN_DIR:")
with pd.option_context('display.max_rows', None, 'display.max_colwidth', 1000,
                       'display.width', None):
    display(pd.DataFrame(preview_rows))

KeyboardInterrupt:

In [ ]:
subjects = sorted(p.name for p in LISTEN_DIR.glob('sub-*'))
print(f"{len(subjects)} subjects: {subjects[0]} ... {subjects[-1]}")

meg_dir = LISTEN_DIR / subjects[0] / 'ses-01' / 'meg'
sorted(p.name for p in meg_dir.iterdir())

58 subjects: sub-01 ... sub-58

['sub-01_ses-01_acq-calibration_meg.dat',
 'sub-01_ses-01_acq-crosstalk_meg.fif',
 'sub-01_ses-01_coordsystem.json',
 'sub-01_ses-01_task-listen_run-01_channels.tsv',
 'sub-01_ses-01_task-listen_run-01_events.tsv',
 'sub-01_ses-01_task-listen_run-01_meg.fif',
 'sub-01_ses-01_task-listen_run-01_meg.json',
 'sub-01_ses-01_task-listen_run-02_channels.tsv',
 'sub-01_ses-01_task-listen_run-02_events.tsv',
 'sub-01_ses-01_task-listen_run-02_meg.fif',
 'sub-01_ses-01_task-listen_run-02_meg.json',
 'sub-01_ses-01_task-listen_run-03_channels.tsv',
 'sub-01_ses-01_task-listen_run-03_events.tsv',
 'sub-01_ses-01_task-listen_run-03_meg.fif',
 'sub-01_ses-01_task-listen_run-03_meg.json',
 'sub-01_ses-01_task-listen_run-04_channels.tsv',
 'sub-01_ses-01_task-listen_run-04_events.tsv',
 'sub-01_ses-01_task-listen_run-04_meg.fif',
 'sub-01_ses-01_task-listen_run-04_meg.json',
 'sub-01_ses-01_task-listen_run-05_channels.tsv',
 'sub-01_ses-01_task-listen_run-05_events.tsv',
 'sub-01_ses-01_task-listen_run-05_meg.fif',
 'sub-01_ses-01_task-listen_run-05_meg.json',
 'sub-01_ses-01_task-listen_run-06_channels.tsv',
 'sub-01_ses-01_task-listen_run-06_events.tsv',
 'sub-01_ses-01_task-listen_run-06_meg.fif',
 'sub-01_ses-01_task-listen_run-06_meg.json',
 'sub-01_ses-01_task-listen_run-07_channels.tsv',
 'sub-01_ses-01_task-listen_run-07_events.tsv',
 'sub-01_ses-01_task-listen_run-07_meg.fif',
 'sub-01_ses-01_task-listen_run-07_meg.json',
 'sub-01_ses-01_task-listen_run-08_channels.tsv',
 'sub-01_ses-01_task-listen_run-08_events.tsv',
 'sub-01_ses-01_task-listen_run-08_meg.fif',
 'sub-01_ses-01_task-listen_run-08_meg.json',
 'sub-01_ses-01_task-listen_run-09_channels.tsv',
 'sub-01_ses-01_task-listen_run-09_events.tsv',
 'sub-01_ses-01_task-listen_run-09_meg.fif',
 'sub-01_ses-01_task-listen_run-09_meg.json']